### PR TITLE
Test

### PR DESCRIPTION
**Pull request by gschri**
Test pull request

### CODE REVIEW

**Comment by AnianZ** [comment]
This is just testing the steps in the tutorial via a pull request, isn't it? Or does it add something to the repo?

**Comment by nelsonic** [comment]
@AnianZ yes, just a test. probably doesn't need to be merged. (_unless it adds something later..._)
thanks for checking. 👍

**Comment by iteles** [comment]
Also the changing of the author information. 

@gschri, I suspect you may have been wanting to open this PR to your own fork rather than to the original repo? :blush:

**Comment by AnianZ** [comment]
Yeah. Seems quite obvious. :smile: Just wanted to make sure.

**Pull request closed without merging**
