### PR TITLE
Secure environment variables

### PR DESCRIPTION
**Pull request by nelsonic**
# Get Excited!

+ Adds section on Environment Variables
+ Adds link to a more detailed example (Learn TDD) which has a more practical example for Travis-CI
+ Adds link to https://github.com/nelsonic/learn-environment-variables tutorial ...

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles please review and merge if happy.
Also we need to tweet the fact that we have updated our tutorial (*finally*)
My suggestion would be:
>"Are you using Continuous Integration to Test the Build of your @nodejs projects?
We just updated our Tutorial on using @TravisCI so its easier than ever to get started!"

Or words to that effect.
and use the image: 
passing
https://raw.githubusercontent.com/dwyl/repo-badges/master/highresPNGs/build-passing.png

Thanks!

**Comment by nelsonic** [comment]
@iteles thanks for reviewing/merging. please paste link to tweet so we can re-tweet. thanks!

**Comment by iteles** [comment]
https://twitter.com/dwylhq/status/636973678358609920

**Comment by nelsonic** [comment]
Sweet. thanks! :tada:

**Pull request merged**
