### PR TITLE
README.ru-RU.md

### LINKED ISSUE #46: Russian translation
I want to translate this guide into Russian, how can I do this?

### PR DESCRIPTION
**Pull request by bogachenko**
Привет @nelsonic :ru: :sunny:

I here from idleness decided to translate your management into Russian and at the same time to close this question (fix #46 ). The guy who opened this question, apparently put his dick on the Russian language. SO.

Спасибо.

### CODE REVIEW

**Comment by bogachenko** [comment]
What the fuck with travis?

**Comment by lex111** [comment]
> apparently put his dick on the Russian language. 

I really wanted to make the translation, but for personal reasons I could not do it, and later forgot about it, but this is a strong word and very rude, but it's good that now there is...

**Comment by nelsonic** [comment]
@lex111  I initially thought it was a typo 😕 
agree that that the expression is "rude" but I didn't think it was intended to be offensive. 

We ❤️ that you opened the issue for the Russian Translation and totally understand that you have many demands on your time. I feel that it's _useful_ to the community of people who don't have english as their first language to have translations so hopefully this will be good for sharing knowledge.

Thanks again all. ✨

**Comment by bogachenko** [comment]
> 
> 
> > apparently put his dick on the Russian language.
> 
> I really wanted to make the translation, but for personal reasons I could not do it, and later forgot about it, but this is a strong word and very rude, but it's good that now there is...

извини, я не знал.

**Pull request merged**
